# https://starship.rs/config/

add_newline = false
format = "${custom.hr}$time$all$line_break$character"
[directory]
style="032" #0087D7
[git_branch]
style="105"

[custom.hr]
command="printf '%.s~' $(seq 1 $COLUMNS)"
style='#6A9FB5' # Orange - #FE8019
when=true

[time]
disabled = false
format = '[$time]($style) '

# [line_break]
# disabled = false

[character]
success_symbol = """
"""
error_symbol = '''
'''
# disabled = true

[status]
disabled = false
# format = '$status'

# format = '[$symbol$common_meaning$status]($style) '
# symbol = '''
# '''
# Map common exit codes to descriptions (optional)
# map_symbol = true
# format = '[$symbol $status]($style) '

# # af-magic.zsh-theme
# # Repo: https://github.com/andyfleming/oh-my-zsh
# # Direct Link: https://github.com/andyfleming/oh-my-zsh/blob/master/themes/af-magic.zsh-theme

# if [ $UID -eq 0 ]; then NCOLOR="red"; else NCOLOR="green"; fi
# local return_code="%(?..%{$fg[red]%}%? â†µ%{$reset_color%})"

# # primary prompt
# PROMPT='\
# $FG[237]---------%{$reset_color%}
# $FG[032]%~\
# $(git_prompt_info)\
#  $FG[105]>%{$reset_color%} \
# '
# PROMPT2='%{$fg[red]%}\ %{$reset_color%}'
# # RPS1='${return_code}'

# # color vars
# eval my_gray='$FG[237]'
# eval my_orange='$FG[214]'

# # git settings
# ZSH_THEME_GIT_PROMPT_PREFIX="$FG[075]($FG[078]"
# ZSH_THEME_GIT_PROMPT_CLEAN=""
# ZSH_THEME_GIT_PROMPT_DIRTY="$my_orange*%{$reset_color%}"
# ZSH_THEME_GIT_PROMPT_SUFFIX="$FG[075])%{$reset_color%}"
